apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-agent
  namespace: jenkins # 将 SA 创建在 jenkins 命名空间
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-agent-role
  namespace: ctfd # 在 ctfd 命名空间创建角色
rules:
# 授予 helm upgrade 所需的权限，这里为了方便给了 "全部" 权限
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-agent-rolebinding
  namespace: ctfd # 在 ctfd 命名空间进行绑定
subjects:
- kind: ServiceAccount
  name: jenkins-agent
  namespace: jenkins # 引用 jenkins 命名空间的 SA
roleRef:
  kind: Role
  name: jenkins-agent-role
  apiGroup: rbac.authorization.k8s.io